### ISSUE TITLE
Error: Couldn't find property ~1 of ...

### ISSUE THREAD

**Issue by MikeRalphson** [atlassian/better-ajv-errors#23]
When `ajv` returns JsonPointers containing `~0` or `~1` replacements (for `~` and `/`), `better-ajv-errors` seems to fail to be able to find the cause of the error:

```text
Couldn't find property ~1 of /paths/~1/GET
Error: Couldn't find property ~1 of /paths/~1/GET
    at pointers.reduce (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/json/get-meta-from-path.js:15:19)
    at Array.reduce (<anonymous>)
    at getMetaFromPath (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/json/get-meta-from-path.js:9:19)
    at AdditionalPropValidationError.getLocation (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/validation-errors/base.js:20:47)
    at AdditionalPropValidationError.getCodeFrame (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/validation-errors/base.js:28:64)
    at AdditionalPropValidationError.print (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/validation-errors/additional-prop.js:25:31)
    at customErrorToText (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/index.js:21:44)
    at Array.map (<anonymous>)
    at exports.default (/home/mike/nodejs/oas-kit/packages/oas-validator/node_modules/better-ajv-errors/lib/modern/index.js:31:25)
    at schemaValidate (/home/mike/nodejs/oas-kit/packages/oas-validator/index.js:1306:30)
```

**Comment by torifat** [comment]
It would be great if you could give us some input.

Sorry for the delay for some reason I didn't get any email notifications from this repo.

**Comment by MikeRalphson** [comment]
@torifat what kind of additional input do you need?

[This TODO comment](https://github.com/torifat/better-ajv-errors/blob/master/src/json/get-meta-from-path.js#L6) seems relevant, and that it's a known issue.
