### ISSUE TITLE
AJV Version 8.0.5 TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by thegalah** [atlassian/better-ajv-errors#90]
AJV  Version 8.0.5

Repro:
```typescript
import * as schema from "./validation.schema.json";
import Ajv, { Options } from "ajv";
import betterAjvErrors from "better-ajv-errors";
import { ISchema, schemas } from "./SchemaDefinition";

const validator = new Ajv({ jsonPointers: true } as Options);
validator.compile(schema);

export const validatePacket = <T extends keyof typeof schemas>(
    data: unknown,
    schemaKeyRef: T
): data is ISchema[T] => {
    validator.validate(schemaKeyRef as string, data);
    if (validator.errors) {
        try {
            const output = betterAjvErrors(schema, data, validator.errors);
            console.log(output);
        } catch (e) {
            console.log(e);
        }
    }
    return Boolean(validator.errors) === false;
};

```

```
TypeError: Cannot read property 'match' of undefined
    at /app/node_modules/better-ajv-errors/lib/modern/helpers.js:26:53
    at Array.forEach (<anonymous>)
    at makeTree (/app/node_modules/better-ajv-errors/lib/modern/helpers.js:21:13)
    at _default (/app/node_modules/better-ajv-errors/lib/modern/helpers.js:116:16)
    at Object._default [as default] (/app/node_modules/better-ajv-errors/lib/modern/index.js:27:45)
```

**Comment by yoshigev** [comment]
Happened to us too.
This is probably due to the following [breaking change](https://github.com/ajv-validator/ajv/blob/master/docs/v6-to-v8-migration.md#new-features) of AJV 8:

> `dataPath` property replaced with `instancePath`

cc @orgads

**Comment by evert** [comment]
I'm sorry for having to ask this (I don't like getting these myself), but is this library still maintained?

We need the latest AJV to get access to the latest json-schema draft, and better-ajv-errors is holding us back. I need to decide if it's worth waiting, or if I should switch back to `worse-ajv-errors` ;)

**Comment by orgads** [comment]
We worked around this issue with this, before sending the errors to betterAjvErrors:

```typescript
  for (const error of errors) {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore Workaround https://github.com/atlassian/better-ajv-errors/issues/90
    error.dataPath = error.instancePath;
  }
```
